name: Release build
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Packages
              run: |
                  sudo apt update -qq
                  sudo apt install -y cmake gcc ninja-build
                  sudo apt install -y libsdl2-dev libsdl2-ttf-dev

            - name: Create Build Directory
              run: |
                  mkdir -p ${{github.workspace}}/build

            - name: Configure CMake
              run: CC=gcc CXX=g++ cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

            - name: Build
              run: ninja -C build
